version: '3.9'

services:
    message-queue:
        image: rabbitmq:3.9.5-management-alpine
        container_name: message-queue
        restart: unless-stopped
    db-dev:
        image: mongo
        container_name: db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: IDDE
        restart: unless-stopped
        profiles: ["dev"]

    api-dev:
        image: registry.gitlab.com/farago322/reactive-idde:latest
        container_name: api
        ports:
            - '8080:8080'
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_DATA_MONGODB_HOST: db-dev
            SPRING_DATA_MONGODB_PORT: 27017
            SPRING_DATA_MONGODB_USERNAME: admin
            SPRING_DATA_MONGODB_PASSOWRD: admin
            SPRING_DATA_MONGODB_DATABASE: IDDE
            SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
            SPRING_RABBITMQ_HOST: message-queue
            SPRING_RABBITMQ_PORT: 5672
        depends_on:
            - db-dev
            - message-queue
        restart: unless-stopped
        profiles: ["dev"]

    api-prod:
        image: registry.gitlab.com/farago322/reactive-idde:latest
        container_name: api
        ports:
            - '8080:8080'
        environment:
            SPRING_PROFILES_ACTIVE: prod
            SPRING_RABBITMQ_HOST: message-queue
            SPRING_RABBITMQ_PORT: 5672
        depends_on:
            - message-queue
        restart: unless-stopped
        profiles: ["prod"]

networks:
    default:
        name: reactive-frim1910
