spring:
    data:
        mongodb:
            username: admin
            password: admin
            host: localhost
            port: 27017
            database: IDDE
            authentication-database: admin
            auto-index-creation: true
